version: '3.4'

networks:
  frontend:
  backend:

services:
  eventscatalogapi:
    image: events/ecatalogapi
    build:
      context: .\EventsCatalogAPI
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalEventBaseUrl: http://localhost:6080
    ports:
      - "6080:80"
    container_name: ecatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5208
    ports:
      - "6070:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.155:6070
      ConnectionString: basket.data
    ports:
      - "6065:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.155:6070
      SQLSERVER_HOST: mssqlserver
      SA_PASSWORD: ProductApi(!)
      DATABASE: OrdersDb
    ports:
      - "6075:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webshop
    environment:
      EventUrl: http://eventscatalogapi
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.155:6070
      CallBackUrl: http://localhost:5208
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_WBsZjG5kBd5zpeS5QDQi8jsm00Wt0yXvfW
      StripePrivateKey: sk_test_w6OinVnMa1i8VV1oJDLq4kTA00uoYiDSTs
    ports:
      - "5208:80"
    networks:
      - frontend
    depends_on:
      - eventscatalogapi
      - tokenserver
      - cart
      - order

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: eventssqlserver
    ports:
      - "1448:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6079:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
      - "5674:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - backend